apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blogd.fullname" . }}
  labels:
    {{- include "blogd.labels" . | nindent 4 }}
data:
  nginx.conf: |
    upstream django {
        server unix:///opt/blogd/sockets/blogd.sock;
    }
    server {
      listen 0.0.0.0:80;
      server_name mtuktarov.com www.mtuktarov.com;
      client_max_body_size 100M;
      root /opt/blogd;
      include uwsgi_params;

      location / {
        proxy_set_header     Host $host;
        proxy_set_header     X-Real-IP $remote_addr;
        proxy_set_header     Upgrade $http_upgrade;
        proxy_set_header     Connection 'upgrade';
        proxy_cache_bypass   $http_upgrade;
        uwsgi_pass           django;
      }

      location /static {
        alias /opt/blogd/collectedstatic;
        expires 1h;
      }

      location /media {
        alias /opt/blogd/media;
        expires 1h;
      }
    }

    server {
      listen 0.0.0.0:80 default;
      server_name _;
      location /200ok {
        return 200;
      }
    }
  djangoDebug: {{ .Values.django.debug | quote }}
  djangoDbName: {{ .Values.django.db.name | quote }}
  djangoDbHost: {{ .Values.django.db.host | quote }}
  djangoSuEmail: {{ .Values.django.superuser.email | quote }}
  djangoEmailHost: {{ .Values.django.smtp_email.host | quote }}
  djangoEmailPort: {{ .Values.django.smtp_email.port | quote }}
  djangoSiteDomainName: {{ .Values.django.siteDomainName | quote }}
  djangoAutomaticMigrations: {{ .Values.django.db.automaticMigrations | quote }}
  djangoDisableCache: {{ .Values.django.disableCache | quote }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
data:
  log-format-upstream: '{ "time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "realip_remote_addr": "$realip_remote_addr", "x-forward-for": "$proxy_add_x_forwarded_for", "request_id": "$request_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" }'
