apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blogd.fullname" . }}
  labels:
    {{- include "blogd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blogd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blogd.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}-nginx
        configMap:
          name: {{ .Chart.Name }}
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: shared-data
        emptyDir: {}
      - name: media-volume
        hostPath:
          path: /data_media
          type: Directory
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-storage
        image: alpine/git
        command: ['sh', '-c', 'chown -R 101:101 /opt /media']
        volumeMounts:
        - name: shared-data
          mountPath: /opt/blogd/
          readOnly: false
        - name: media-volume
          mountPath: /media
          readOnly: false

      serviceAccountName: {{ include "blogd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: BRANCH
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: branch
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoDbHost
          - name: PGNAME
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoDbName
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoDbUser
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoDbPassword
          - name: DJANGO_SITE_DOMAIN_NAME
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoSiteDomainName
          - name: DJANGO_SU_NAME
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoSuName
          - name: DJANGO_SU_PASSWORD
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoSuPassword
          - name: DJANGO_SU_EMAIL
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoSuEmail
          - name: DJANGO_DISABLE_CACHE
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsDisableCache
          - name: DJANGO_EMAIL_HOST
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoEmailHost
          - name: DJANGO_EMAIL_PORT
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: djangoEmailPort
          - name: DJANGO_EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoEmailUser
          - name: DJANGO_EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name: blogd
                key: djangoEmailPassword
          - name: DJANGO_DISABLE_CACHE
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsDisableCache
          - name: WAIT_FOR_POSTGRES
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsWait_postgres
          - name: ADD_SUPERUSER
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsAdd_superuser
          - name: CONFIGURE_GROUPS
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsConfigure_groups
          - name: RENAME_SITE
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsRename_site
          - name: MAKEMIGRATIONS
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsMakemigrations
          - name: MIGRATE
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsMigrate
          - name: COLLECT_STATIC
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsCollect_static
          - name: COMPRESS_STATIC
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: actionsCompress_static
          - name: UWSGI_PARAMS
            valueFrom:
              configMapKeyRef:
                name: blogd
                key: uwsgi_params
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: shared-data
            mountPath: /opt/blogd/
            readOnly: false
          - name: media-volume
            mountPath: /media
            readOnly: false

        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /200ok
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
               path: /200ok
               port: 80
          resources:
            {{- toYaml .Values.nginxResources | nindent 12 }}
          volumeMounts:
          - name: {{ .Chart.Name }}-nginx
            mountPath: /etc/nginx/conf.d/
            readOnly: false
          - name: shared-data
            mountPath: /opt/blogd/
            readOnly: false
          - name: media-volume
            mountPath: /opt/blogd/media
            readOnly: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
