apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blogd.fullname" . }}
  labels:
    {{- include "blogd.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.django.db.password -}}
  djangoDbPassword: {{ .Values.django.db.password | b64enc | quote }}
  {{ else -}}
  djangoDbPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}
  djangoDbUser: {{ .Values.django.db.user | b64enc | quote }}
  {{- if .Values.django.superuser.password }}
  djangoSuPassword: {{ .Values.django.superuser.password | b64enc | quote }}
  {{ else -}}
  djangoSuPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}
  djangoSuName: {{ .Values.django.superuser.name | b64enc | quote }}
  {{- if .Values.django.smtp_email.password }}
  djangoEmailPassword: {{ .Values.django.smtp_email.password | b64enc | quote }}
  {{- end -}}
  {{- if .Values.django.smtp_email.user }}
  djangoEmailUser: {{ .Values.django.smtp_email.user | b64enc | quote }}
  {{- end -}}
