{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blogd.serviceAccountName" . }}
  labels:
{{ include "blogd.labels" . | nindent 4 }}
{{- end -}}
