---

- name: k8s_master/tasks/init.yml - Reset Kubernetes component
  tags:
  - k8s-init-master
  - k8s-master
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: k8s_master/tasks/init.yml - Init Kubernetes cluster
  tags:
  - k8s-init-master
  - k8s-master
  when: reset_cluster is succeeded
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 {{ kubeadm_opts }}
  register: init_cluster

- name: k8s_master/tasks/init.yml - Create Kubernetes config directory
  tags:
  - k8s-init-master
  - k8s-master
  file:
    path: ".kube/"
    state: directory

- name: k8s_master/tasks/init.yml - Copy admin.conf to Home directory
  tags:
  - k8s-init-master
  - k8s-master
  when: init_cluster is succeeded
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true

- name: k8s_master/tasks/init.yml - untain master
  tags:
  - k8s-init-master
  - k8s-master
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: init_cluster is succeeded
